const symbolGroups = [
  {
    name: "Greek",
    symbols: [
      { label: "α", latex: "\\alpha" },
      { label: "β", latex: "\\beta" },
      { label: "γ", latex: "\\gamma" },
      { label: "δ", latex: "\\delta" },
      { label: "ε", latex: "\\varepsilon" },
      { label: "θ", latex: "\\theta" },
      { label: "λ", latex: "\\lambda" },
      { label: "μ", latex: "\\mu" },
      { label: "π", latex: "\\pi" },
      { label: "ρ", latex: "\\rho" },
      { label: "σ", latex: "\\sigma" },
      { label: "τ", latex: "\\tau" },
      { label: "φ", latex: "\\phi" },
      { label: "χ", latex: "\\chi" },
      { label: "ψ", latex: "\\psi" },
      { label: "ω", latex: "\\omega" },
      { label: "Γ", latex: "\\Gamma" },
      { label: "Δ", latex: "\\Delta" },
      { label: "Θ", latex: "\\Theta" },
      { label: "Λ", latex: "\\Lambda" },
      { label: "Π", latex: "\\Pi" },
      { label: "Σ", latex: "\\Sigma" },
      { label: "Φ", latex: "\\Phi" },
      { label: "Ω", latex: "\\Omega" },
    ],
  },
  {
    name: "Operators",
    symbols: [
      { label: "±", latex: "\\pm" },
      { label: "∓", latex: "\\mp" },
      { label: "×", latex: "\\times" },
      { label: "÷", latex: "\\div" },
      { label: "⋅", latex: "\\cdot" },
      { label: "≠", latex: "\\neq" },
      { label: "≈", latex: "\\approx" },
      { label: "≡", latex: "\\equiv" },
      { label: "≤", latex: "\\leq" },
      { label: "≥", latex: "\\geq" },
      { label: "≪", latex: "\\ll" },
      { label: "≫", latex: "\\gg" },
      { label: "∝", latex: "\\propto" },
      { label: "∼", latex: "\\sim" },
      { label: "°", latex: "^\\circ" },
      { label: "∠", latex: "\\angle" },
    ],
  },
  {
    name: "Sets & logic",
    symbols: [
      { label: "∈", latex: "\\in" },
      { label: "∉", latex: "\\notin" },
      { label: "⊂", latex: "\\subset" },
      { label: "⊆", latex: "\\subseteq" },
      { label: "⊃", latex: "\\supset" },
      { label: "∪", latex: "\\cup" },
      { label: "∩", latex: "\\cap" },
      { label: "∅", latex: "\\emptyset" },
      { label: "∀", latex: "\\forall" },
      { label: "∃", latex: "\\exists" },
      { label: "¬", latex: "\\neg" },
      { label: "∧", latex: "\\land" },
      { label: "∨", latex: "\\lor" },
      { label: "ℕ", latex: "\\mathbb{N}" },
      { label: "ℝ", latex: "\\mathbb{R}" },
      { label: "ℤ", latex: "\\mathbb{Z}" },
    ],
  },
  {
    name: "Calculus",
    symbols: [
      { label: "∑", latex: "\\sum_{}^{}" },
      { label: "∏", latex: "\\prod_{}^{}" },
      { label: "∫", latex: "\\int_{}^{}" },
      { label: "∬", latex: "\\iint" },
      { label: "∮", latex: "\\oint" },
      { label: "∂", latex: "\\partial" },
      { label: "∇", latex: "\\nabla" },
      { label: "∞", latex: "\\infty" },
      { label: "lim", latex: "\\lim_{}" },
      { label: "→", latex: "\\to" },
      { label: "←", latex: "\\leftarrow" },
      { label: "↔", latex: "\\leftrightarrow" },
      { label: "⇒", latex: "\\Rightarrow" },
      { label: "⇐", latex: "\\Leftarrow" },
      { label: "⇔", latex: "\\Leftrightarrow" },
      { label: "↦", latex: "\\mapsto" },
    ],
  },
  {
    name: "Structures",
    symbols: [
      { label: "a⁄b", latex: "\\frac{}{}", title: "Fraction" },
      { label: "xⁿ", latex: "^{}", title: "Superscript" },
      { label: "xₙ", latex: "_{}", title: "Subscript" },
      { label: "√", latex: "\\sqrt{}", title: "Square root" },
      { label: "ⁿ√", latex: "\\sqrt[]{}", title: "Nth root" },
      { label: "x̄", latex: "\\bar{}", title: "Bar" },
      { label: "x̂", latex: "\\hat{}", title: "Hat" },
      { label: "x⃗", latex: "\\vec{}", title: "Vector" },
      { label: "(…)", latex: "\\left( \\right)", title: "Auto-sized brackets" },
      {
        label: "[…]",
        latex: "\\begin{bmatrix} \\end{bmatrix}",
        title: "Matrix",
      },
      { label: "{…", latex: "\\begin{cases} \\end{cases}", title: "Cases" },
      { label: "⋯", latex: "\\cdots", title: "Centred ellipsis" },
    ],
  },
];

export default symbolGroups;
